# -*- coding: utf-8 -*-
"""LanierBot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16BVMmBDd9nuYG7PQ3WHanerWdJ6kyGze

# Install dependencies
"""

# Commented out IPython magic to ensure Python compatibility.
# !pip install gpt-index
# !pip install pinecone-client
# !pip install gradio
# requireds %env OPENAI_API_KEY

"""# Set up the index"""

# We've already created the index in another script before running this.
import pinecone
from gpt_index import GPTPineconeIndex
from gpt_index.data_structs.data_structs import PineconeIndexStruct

pinecone_api_key = os.environ['PINECONE_API_KEY']
pinecone.init(api_key=pinecone_api_key, environment="us-west1-gcp")
pinecone_index = pinecone.Index("lanier")
# Load the existing index
index = GPTPineconeIndex(pinecone_index=pinecone_index,
                         index_struct=PineconeIndexStruct())

"""#Create the function"""

import gradio as gr

def answer_question(question):
    response = index.query(question, verbose=True)
    return response

demo = gr.Interface(fn=answer_question, inputs="text", outputs="text")

demo.launch(share=True)